CREATE DATABASE IF NOT EXISTS irc;

USE irc;

CREATE TABLE IF NOT EXISTS room (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nom VARCHAR(255) NOT NULL
);

ALTER TABLE room ADD UNIQUE(nom);

CREATE TABLE IF NOT EXISTS user (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);

ALTER TABLE user ADD UNIQUE(username);